### ISSUE TITLE
New HM protocol causes CC memory leak

### ISSUE THREAD

**Issue by d** [cloudfoundry-attic/health_manager#6]
Commit cloudfoundry/health_manager@f5df45e includes a nested hash under key "running" with the form
{"version" => num_running} [https://github.com/cloudfoundry/health_manager/commit/f5df45e6352298a8fb5b1671c650d1f07f62e157#L1R67].
The fact that cf-message-bus decodes messages and symbolizes the keys in the hash cloudfoundry/cf-message-bus@c243e5e#L93 means that if Cloud Controller subscribes to the new channel HM will slowly creep up the memory in cloud controllers.
- The ideal fix seems involve fixing CC (and hence cf-message-bus) but involves making backwards incompatible change to a common library and needs coordination
- The short term fix could be changing the payload under "running" to be an array of (version, running_num) pairs.
- Of course the quickest fix is to say that "who cares about memory leak, can you even write a test for it?"

**Comment by mkocher** [comment]
Nice catch

**Comment by jfoley** [comment]
@MarkKropf - Is this still an issue?

@aramprice / @jfoley

**Comment by MarkKropf** [comment]
@jfoley Yes it is, checking for the corresponding story to see why it hasn't gone through yet.

**Comment by mmb** [comment]
@MarkKropf Any updates on this one?

@mmb / @matthewmcnew

**Comment by mariash** [comment]
I am pretty sure we fixed this issue some time ago. We are using stringyfied keys in message bus now and CC was updated to use new version.

**Comment by adamstegman** [comment]
@mariash This issue looks pretty old. Could you confirm if this has been resolved?

CF Community Pair (@adamstegman & @mbhave)

**Comment by mkocher** [comment]
Zombie Repo. I'll schedule this for moving into the attic.
