### ISSUE TITLE
HM /varz is missing info about users

### ISSUE THREAD

**Issue by duglin** [cloudfoundry-attic/health_manager#9]
@MarkKropf 

In v1 the HM /varz json included the list of users (emails) and this is currently missing from the v2 code.  There is a "users" field in the JSON but it is an empty array.  For our environment we use this information in an admin UI so its kind of important to us.  We'd prefer to avoid accessing the DBs directly and continue to use the /varz data instead.  While ideally we'll need to discuss how to expose orgs and spaces, for now we wanted to start small and just include the list of users.

We have the code/patch needed to enhance the HM /varz to include this data but before we issued a pull request we wanted to discuss the issue to make sure this is still the correct approach.

**Comment by mkocher** [comment]
Architecturally HM knows nothing about users, I'm not sure why it ever included them in /varz. Can you not get the information you need out of the CC API?

**Comment by duglin** [comment]
By CC API, do you mean CC /varz?  We can certainly make it part of the Cloud Controller /varz instead - I think it does make more sense over there. We just weren't sure if the dangling "users" field in the HM /varz was a placeholder or a relic  :-)

**Comment by mkocher** [comment]
Nope, I mean the main cc api.  What exact data are you trying to retrieve?

**Comment by duglin** [comment]
Right now just the list of users/emails - but eventually we'd like to also pull back the list of orgs and spaces and then show how all 3 are related.

Whether we use the cc api or the varz api doesn't really matter much in the end, but I do think having a consistent pattern is probably important.  So, perhaps I should ask whether the /varz endpoints are going to be maintained going forward?  If so, then it seems logical to include this stuff in there because having to get some data via /varz but other data via a different type of mechanism is kind of confusing and tedious.  Personally, I like the varz stuff - it is a very convenient way to get all info (basic and pretty low level) about a CF component in one shot. 

But, if the varz endpoints are deprecated then we need to make sure all the same info is available via some other means.  Has there been any discussion about the future of the varz stuff?

**Comment by mkocher** [comment]
The /varz endpoints are intended for collecting statistics, not containing data for end users, even an admin panel.  I suspect you can get everything you need out of the normal API that Cloud Controller provides.  Lets move this discussion over there if you aren't able to get the data out that you need.
